language: java
sudo: true
before_install:
- sudo rm -f /etc/mavenrc
- wget http://www.us.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
- tar -zxvf apache-maven-3.0.5-bin.tar.gz
- export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
- export M2_HOME=$PWD/apache-maven-3.0.5
- export PATH=$M2_HOME/bin:$PATH
- mvn --version
- rvm install 2.4.1
- gem install travis-custom-deploy
script:
- gradle createPoms
- gradle downloadCli
- gradle collectDependencies
- mvn -f de.prob.parent/pom.xml install
- gradle collectArtifacts
branches:
  only:
  - develop
jdk:
- oraclejdk8
after_success:
- travis-custom-deploy sftp updatesite/
env:
  global:
  - secure: EBtNmeY6KPX+MMmEwd4+GJWkWJ4mQ4R+yV0O0Uu4/9QoO/6InUEMbeRJt3xYQ9ewjKMNPLY85EknZxBUWvJURyOicmuP1gbHYEfYjIYbbZrAE+82NDtbhe6eUjlAIpms/q7WZ78IEvghUeO6mnsPiJ0hmm0tVlQz5khHsm10wGs=
  - secure: JPHuiS+3J/AyEFr0v6MlS3MamX1Ebo7NcoDOBEfhyjfTErDnyvvbeoxPb0Fm+12fL+b6lxDi9pV8R+Z2x65vxXk2n3wcChklpBrno+VVSKBrkswy+YxAMUKkG4ssei2smA846NyeyTipPqhtbTHkV5q5mabxPzoE4x19uOfwRX0=
  - secure: M6zqQ6zwRadCAkaLcyADPGFx3BgAKWHS41X0O8RcqKA+kbRG5MshN3HcMy847p2elS4kaCm3X2uo/9SuoXpR/nWIRaM980QcyUJh1gdJBpIA7uOOtpT8XbFZVxnlMvhI0uFzLIlA8sRLzZOcCFzEiHctuO9iZxEyXxbs/SvqV5M=
  - secure: UeQaG2wcFEPt9DxHcGIZkrshfvPZ/7AdJcX/3B4juHATNr5arJf227uOdRRRAoyCouFDuPa2HMLsfIWPQOSCwAuCL+jvM8ebQ0snc/lHnG6VvTu9m549bMfQO6Nw4NGYCbSsfn2XMppi6OZ5s5jck8SubELgTSZxtWGiJ/IJTrU=
