import java.util.concurrent.TimeUnit

// to trigger a full tycho build please use 'gradle deleteFromClassPath completeInstall'

project.ext {
	// The newest Bundle-RuntimeExecutionEnvironment required any of the build dependencies (Eclipse and Rodin).
	// Currently Java 21 since Rodin 3.10.
	buildTimeExecutionEnvironment = "JavaSE-21"

	targetRepositories = [
		"https://download.eclipse.org/releases/2025-12/", // Eclipse 4.38
		"https://rodin-b-sharp.sourceforge.net/core-updates/3.10/",
		"https://rodin-b-sharp.sourceforge.net/updates/Plugin_Theory/4.0.4/",
	]

	groupID = "de.prob"
}

apply from: 'tycho_build.gradle'

allprojects {
	configurations.all {
		resolutionStrategy {
			cacheChangingModulesFor(0, TimeUnit.SECONDS)
		}
	}
}

// When making a release, please check that parserVersion matches what the specified version of probcli expects, to avoid unpredictable/inconsistent behavior!
def parserVersion = "2.16.0"
def probcliVersion = "1.16.0-nightly"
def cliDownloadURL
if (probcliVersion.endsWith("-nightly")) {
	cliDownloadURL = "https://stups.hhu-hosting.de/downloads/prob/cli/nightly"
} else {
	cliDownloadURL = "https://stups.hhu-hosting.de/downloads/prob/cli/releases/${probcliVersion}"
}

project(':de.prob.core') {
	apply plugin: "java"

	final snapshotsRepoUrl = "https://central.sonatype.com/repository/maven-snapshots/"
	repositories {
		mavenCentral()
		maven {
			name = "Sonatype snapshots"
			url = snapshotsRepoUrl
		}
	}

	dependencies {
		// Note: After changing/updating dependencies or their versions here,
		// run "./gradlew clean setClassPath prepareMaven".
		// This downloads the dependencies and configures them in all appropriate places.
		// If you updated or removed any dependencies,
		// you also need to *manually* delete the old dependencies/versions
		// from the relevant .classpath and META-INF/MANIFEST.MF files.
		implementation("de.hhu.stups:answerparser:${parserVersion}")
		implementation("de.hhu.stups:bparser:${parserVersion}")
		implementation("de.hhu.stups:ltlparser:${parserVersion}")
		implementation("de.hhu.stups:parserbase:${parserVersion}")
		implementation("de.hhu.stups:prologlib:${parserVersion}")
		implementation("de.hhu.stups:unicode:${parserVersion}")
		implementation("de.hhu.stups:theorymapping:${parserVersion}")
	}
}

project(":de.bmotionstudio.gef.editor") {
	apply(plugin: "java")

	repositories {
		mavenCentral()
	}

	dependencies {
		implementation("com.thoughtworks.xstream:xstream:1.4.20")
		// Current versions of XStream depend on MXParser, but not any specific version of it.
		// To avoid the version number changing unexpectedly and breaking the MANIFEST.MF classpath entries,
		// hardcode a specific MXParser version here.
		// It *should* be safe to update this when a new version is released.
		implementation("io.github.x-stream:mxparser:1.2.2")
	}
}

final platforms = [
	"macos",
	"linux64",
	"windows64",
]

def download(address,target) {
	def file = new FileOutputStream(target)
	def out = new BufferedOutputStream(file)
	out << new URL(address).openStream()
	out.close()
}

task downloadCli {
	doLast{
		def dir = workspacePath + 'de.prob.core/prob/'
		delete file(dir)
		new File(dir).mkdirs()

		platforms.each {platform ->
			def targetdir = dir + platform
			def targetzip = dir + "probcli_${platform}.zip"
			def url = "${cliDownloadURL}/probcli_${platform}.zip"
			download(url, targetzip)
			FileTree zip = zipTree(targetzip)
			copy {
				from zip
				into targetdir
			}
			delete file(targetzip)
		}
	}
}


prepareMaven.dependsOn downloadCli

task deleteCli(type: Delete) {
	delete("de.prob.core/prob")
}
clean.dependsOn(deleteCli)
